config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users

  resources :articles

  namespace :admin do

    resources :articles, only: [:destroy, :edit]
    resources :users, only: [:index, :destroy, :edit]
  end

  resources :reviews, only: [:destroy]


  resources :articles do
    resources :reviews, only: [:create, :new, :edit, :update]
    resources :votes, only: [:create]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_many :votes, dependent: :destroy

  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :name, length: {
    minimum: 5,
    maximum: 50
  }

  validates :url, presence: true
  validates :url, :format => URI::regexp(%w(http https))
  validates :url, uniqueness: true

  validates :description, presence: true
  validates :description, length: { maximum: 500 }

  def self.search(search)
    if search
      find(:all, :conditions => ["name ILIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :body, length: { minimum: 25 }, presence: true
  validates :article, :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :reviews

  has_many :votes

  mount_uploader :profile_photo, ProfilePhotoUploader
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates_uniqueness_of :user, scope: [:article, :vote_tally]
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
    before_filter :admin_authorize!

    def destroy
      @article = Article.find(params[:id])
      @article = Article.find(params[:id]).destroy

      if @article.destroy
        redirect_to articles_path, :notice => "Article successfully deleted"
      else
        render :edit
      end
    end

    def edit
      @article = Article.find(params[:id])
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_filter :admin_authorize!
    def index
      @users = User.all
    end

    def destroy
      @user = User.find(params[:id])
      @user = User.find(params[:id]).destroy
      if @user.destroy
        redirect_to admin_users_path, :notice => "User successfully deleted"
      else
        render :edit
      end
    end

    def edit
      @user = User.find(params[:id])
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_authorize!
    if current_user.role != 'admin'
      redirect_to articles_path, notice: "Invalid user"
    end
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :role, :profile_photo]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user!, only: [:destroy, :new, :create, :edit, :update]

  def new
    @article = Article.new
  end

  def create
    @user = User.find(current_user.id)
    @article = @user.articles.build(article_params)

    if @article.save
      redirect_to article_path(@article), notice: "Article successfully added"
    else
      render :new
    end
  end

  def index
    @articles = Article.search(params[:search]).page(params[:page]).per(10)
  end

	def show
		@article = Article.find(params[:id])
		@vote = Vote.new
		@votes = @article.votes
		@reviews = @article.reviews.page(params[:page]).per(10)
	end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if current_user.id != @article.user_id
      redirect_to @article, notice: "Invalid user"
    else
      if @article.update_attributes(article_params)
        redirect_to edit_article_path, notice: "Article successfully edited"
      else
        render :edit
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if current_user.id != @article.user_id
      redirect_to @article, notice: "Invalid user"
    else
      @article = Article.find(params[:id]).destroy
      if @article.destroy
        redirect_to articles_path, notice: "Article successfully deleted"
      else
        render :edit
      end
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :description, :url, :vote_count, :category_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def new
    @review = Review.new
    @article = Article.find(params[:article_id])
  end


  def edit
    @article = Article.find(params[:article_id])
    @review = Review.find(params[:id])
  end


  def update
    @article = Article.find(params[:article_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to article_path(@article), notice: "Review successfully edited"
    else
      redirect_to article_path(@article), notice: "Review did fail"
    end
  end

  def create
    @user = User.find(current_user.id)
    @article = Article.find(params[:article_id])
    @review = Review.new(review_params)
    @reviews = @article.reviews
    @review.article_id = @article.id
    @review.user_id = @user.id

    if @review.save
      UserMailer.review_notice(@article).deliver
      redirect_to article_path(@article), notice: "Review successfully added"
    else
      render :new, notice: "Review did fail"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @article = @review.article

    if @review.destroy
      redirect_to article_path(@article), notice: "Review deleted"
    else
      flash[:notice] = "Review was not deleted"
      render 'show'
    end
  end

  private
  def review_params
    params.require(:review).permit(:body, :user_id, :article_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :update]

  def create
    @article = Article.find(params[:article_id])
    @user = current_user.id
    @reviews = @article.reviews.page(params[:page]).per(10)
    @vote = Vote.new(vote_params)

    if @vote.save
      UserMailer.vote_notice(@article).deliver
      redirect_to article_path(@article), notice: "Your vote has been recorded"
    else
      flash[:notice] = "You have already voted"
      render "articles/show"
    end
  end

  private
  def vote_params
    params.require(:vote).permit(:vote_tally, :user_id, :article_id)
  end

end

app/views/admin/articles/edit.html.erb
<%= button_to 'Delete article', admin_article_path(@article), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/admin/articles/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/admin/articles/show.html.erb
<%= @article.name %>
<%= @article.description %>
<%= @article.url %>
<%if current_user.id == @article.user_id%>
  <%= button_to "Edit", edit_article_path, :class => "button", :method => "get" %>
<%end%>

app/views/admin/users/edit.html.erb
<li><%= @user.name %></li>

<%= button_to 'Delete user', admin_user_path(@user), method: 'delete', data: { confirm: 'Are you sure?' } %>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{@article.errors.count} prevented the article from being saved" %></h2>
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

<div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
<% if current_user.id == @article.user_id || current_user.role == 'admin' %>
  <div class="actions">
   <%= f.submit "Submit" %>
  </div>
<%end%>
  <%end%>

<% if current_user.id == @article.user_id || current_user.role == 'admin' %>
  <%= button_to 'Delete article', article_path(@article), method: 'delete', data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% unless current_user.blank? %>
  <% if current_user %>
    <%= image_tag(current_user.profile_photo) %>
    <% end %>
<% end %>


<%= form_tag articles_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>


<%= paginate @articles %>

  <ul>
    <% @articles.each do |article| %>
      <li><%= link_to article.name, article_path(article) %></li>
      <li>Article votes: <%= article.votes.sum(:vote_tally) %></li>
   <% end %>
 </ul>
      <h4><%= link_to "Add new article", new_article_path %></h4>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{@article.errors.count} prevented the article from being saved" %></h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

<div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.select( :category_id, Category.all.map {|c| [c.topic, c.id]}) %>
  </div>

  <div class="actions">
  <%= f.submit "Submit" %>
  </div>

  <% end %>

app/views/articles/show.html.erb
  		<p>&nbsp;</p>

		<div class="large-6 columns" id="cell">
  			<div class="small-2 columns" id="upvotes">
  				<img id="user-pic" src="/imgs/av_sm_rnd.png">
  				<div id="username"><%= @article.user.name %></div>
  				<br>
  			</div>
  			<div id="article-box">


				<h3 id="titleh3"><b id="article-title"><%= link_to @article.name, @article.url %></b></h3>
  				<h5 id="description"><%= @article.description %></h5>

				<% unless current_user.blank? %>

	  				<div class="small-2 columns" id="upvotes">
						<%= form_for [@article, @vote] do |f| %>
							<%= f.hidden_field "article_id", :value => @article.id %>
							<%= f.hidden_field "user_id", :value => current_user.id %>
							<%= f.hidden_field "vote_tally", :value => 1 %>
							<%= image_submit_tag("/imgs/upvote.png", :class => 'up-vote', :id => "upv-img") %>
						<% end %>


	  				</div>
					<div class="small-2 columns" id="upvotes">
						<%= form_for [@article, @vote] do |f| %>
							<%= f.hidden_field "article_id", :value => @article.id %>
							<%= f.hidden_field "user_id", :value => current_user.id %>
							<%= f.hidden_field "vote_tally", :value => -1 %>
							<%= image_submit_tag("/imgs/downvote.png", :class => 'down-vote', :id => "dnv-img") %>
						<% end %>
					</div>

				<% end %>


  				<div class="small-2 columns" id="upvotes">
					<b id="upvotes-button"><%= @article.votes.sum(:vote_tally) %></b>
  					<a href="#artcile#replies"><img id="repls-img" src="/imgs/replies.png"></a>
					<% reviews = @article.reviews %>
  				  <a href="#artcile#replies"><b id="replies-button"><%= reviews.length %> reviews</b></a>

				  <img id="vline-img" src="/imgs/vline.png">
  				</div>



  				<a id="category" href="#search#category"><span class="radius secondary label"><b><%= @article.category.topic %></b></span></a>


  		  	  	<hr id="move-down-sir"></hr>
  			</div>
  		</div>

	<% unless current_user.blank? %>
		<% if current_user.id == @article.user_id%>
			<%= button_to "Edit Article", edit_article_path(@article.id), :class => "button", :method => "get" %>
		<%end%>
	<%end%>

<% unless current_user.blank? %>
	<%= image_tag(current_user.profile_photo) %>
<% end %>

	  <p>&nbsp;</p>


<div id="reviews">
	<h3>Reviews:</h3>
	<% @reviews.each do |review| %>
  		<div class="large-6 columns" id="cell">
  			<div class="small-2 columns" id="upvotes">
  				<img id="user-pic" src="/imgs/av_sm_rnd.png">
  				<div id="username"><%= review.user.name %></div>
  				<br>
  			</div>
  			<div id="article-box">


  				<h5 id="description"><%= review.body %></h5>

				<% unless current_user.blank? %>
					<% if current_user.id == review.user_id || current_user.role == 'admin' %>
					 <p>&nbsp;</p>
						<%= button_to "Edit Review", edit_article_review_path(review.article_id, review.id), :class => "button tiny", :method => "get" %>
						<%end%>
					<%end%>
  		  	  	<hr id="move-down-sir"></hr>
  			</div>
  		</div>

	<% end %>
</div>

<%= link_to "Add a Review", new_article_review_path(@article) %>

<%= paginate @reviews %>

	  <p>&nbsp;</p>
	  <p>&nbsp;</p>
	  <p>&nbsp;</p>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RÜBBIT</title>

  <link rel="stylesheet" href="/css/index.css">
  <link rel="stylesheet" href="/css/animate.css">

  <script src="/js/jquery.min.js"></script>
  <link rel="stylesheet" href="/css/foundation.min.css">
  <script src="/js/foundation.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

<!-- ---------------------------- Nav Bar --------------------------------- -->
	  	<div class="fixed">
	  		<nav class="top-bar" data-topbar role="navigation">

	  		  <ul class="title-area">
	  		    <li class="name">
	  			 <a href="/"<><img src="/imgs/rbt_logo.png"></a>
	  		    </li>
	  		  </ul>

	  		  <section class="top-bar-section">

	  			<!-- Left Nav Section -->
	  			<ul class="left">

<!-- ----------------- search bar ----------------- -->

	  			<form method="get" action="<%= articles_path %>">
	  				<div class="small-10 columns">
	  				  <input type="text" name="search" placeholder="search for articles" id="search-field">
	  				</div>
	  				<div class="small-2 columns">
	  				  <button id="search-button" type="submit" class="button postfix">Search</button>
	  				</div>
	  			</form>

<!-- ----------------- end of search bar ----------------- -->

	  			</ul>

	  			<!-- Right Nav Section -->
	  			<ul class="right">

			            <%- if current_user -%>
					  <li class="active"><a href="<%= new_article_path %>" id="submit-button">+ Submit Article</a></li>
					   <li><%= link_to 'My Account', edit_user_registration_path %></li>
			              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>


			            <%- else -%>
			              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
			              <li><%= link_to 'Sign In', new_user_session_path %></li>
			            <%- end -%>
	  			</ul>


	  		  </section>

	  		</nav>
	  	</div>
	  <!-- ----------------------------- End (Nav Bar)  -------------------------------- -->


<div class="row">
  <%= yield %>
</div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit Your Review!!</h1>
<%= form_for(@review, :url => {:action => 'update', :id => @review.id}) do |f| %>

<div class="field">
  <%= f.label :body %><br />
  <%= f.text_field :body %>
</div>

<div class="actions">
  <%= f.submit "Save" %>
</div>

<% end %>


  <%= button_to "Delete", @review, :method => :delete %>

app/views/reviews/new.html.erb
<h1>Add a Review</h1>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{@review.errors.count} error prevented the article from being saved" %></h2>
      <ul>
        <% @review.errors.full_messages.each do |review| %>
        <li><%= review %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for ([@article, @review]) do |f| %>

<div class="field">
  <%= f.label :body %>
  <%= f.text_field :body %>
</div>

<div class="actions">
  <%= f.submit "Add Review" %>
</div>

<% end %>